apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-temp-mount
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: stable-diffusion-temp-mount
  template:
    metadata:
      labels:
        app: stable-diffusion-temp-mount
    spec:
      restartPolicy: Always
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-central 

      containers:
      - name: almalinux9
        image: almalinux:9
        command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
        resources:
          limits:
            memory: 8Gi
            cpu: 4
          requests:
            memory: 8Gi
            cpu: 4
        volumeMounts:
        - mountPath: /data
          name: stable-diffusion-data
  
      volumes:

      - name: stable-diffusion-data
        persistentVolumeClaim:
          claimName: twomey-stable-diffusion-data-clone

